### ISSUE TITLE
IMG2GRP scales up input images when it shouldn't

### ISSUE THREAD

**Issue by tomrow** [Perska/IMG2GRP#1]
When running the software, the software seems to modify images during the conversion process, scaling them up in a filtered manner by about 1.5 times. The GRP file result looked very blurry and the far right and bottom of the image was cut off. This causes things like pixel art and sprite sheets to become unusable.

**Comment by Perska** [comment]
Can you provide a test image where this happens?

I'll look into it in the morning.

**Comment by Perska** [comment]
@tomrow

**Comment by tomrow** [comment]
![apple](https://user-images.githubusercontent.com/10169982/102259542-24d21200-3f07-11eb-9ba6-71a65432b051.png)

**Comment by tomrow** [comment]
I tested it with some 32x32 PNG files.
Here was the output file of the previously posted PNG:
[BAPPLE.zip](https://github.com/Perska/IMG2GRP/files/5697953/BAPPLE.zip)

**Comment by Perska** [comment]
fixed in 786dac4dc295f7cc06e09eceb553e5fde0e76bca, new build [here](https://github.com/Perska/IMG2GRP/releases/tag/1.1)
